apiVersion: v1
kind: Secret
metadata:
  namespace: antifraude
  name:  motor-reglas-config # por favor colocar siempre el nombre del namespace definido en 'namespace.yml'
type: Opaque
stringData:
  # en 'data' se debe colocar cada archivo que se va llevar como configuracion al configmap
  application.yml: |
    datasource:
      url: &URL_DB&
      username: &USERNAME_DB&
      password: &PW_DB&
      driverClassName: &DRIVER_CLASS_NAME_DB&     
    